# Generated by Django 5.1.1 on 2024-09-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiKey',
            new_name='WeatherApiKey',
        ),
    ]
